version: '3'
services:
  # Mocks
  mocks:
    build: ./component-test/mocks
    ports:
      - '8884:8884'
      - '9003:9003'
  #App
  app:
    build: ./app
    depends_on:
      - mocks
    links:
      - 'mocks'
    ports:
      - '3000:3000'
    environment:
      - 'REACT_APP_API_URL=http://localhost:9003'